---
title: "Welcome to MotionMeerkat!"
output: html_document
---

### What is MotionMeerkat?

MotionMeerkat is an open source tool designed to find candidate motion events inside video streams.It also provides basic semantic information about objects including time stamp and x,y coordinates within the frame.

### Who should use MotionMeerkat?

Anyone! This tool was made for terrestrial and marine ecologists who are sick of reviewing hours of video data.

### How does MotionMeerkat work? 

MotionMeerkat uses the opencv and ffmpeg python libraries to detect motion using foreground detection followed by contour analysis. For more examples type opencv motion into youtube! Lots of cool uses out there.

### What does MotionMeerkat not do?

The program is not a miracle. If you cannot see your organism in the image, it will not find it. If your organism does not move, MotionMeerkat will not find it. Additional features in the computer vision realm, such as segmentation counting and multi-object tracking could be a added in new versions. If you have ideas about features you'd like to see, let me know:

https://github.com/bw4sz/OpenCV_HummingbirdsMotion/issues/6

### How should I cite MotionMeerkat?

Weinstein, B. G. (2014), MotionMeerkat: integrating motion video detection and ecological monitoring. Methods in Ecology and Evolution. doi: 10.1111/2041-210X.12320